# Generated by Django 5.2.7 on 2025-11-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desig', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('doj', models.DateField()),
            ],
        ),
    ]
