# Generated by Django 5.2.6 on 2025-09-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desig', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('doj', models.DateField()),
            ],
        ),
    ]
